services:
  fuseki:
    image: stain/jena-fuseki
    container_name: hcmo-fuseki
    ports:
      - "3030:3030"
    environment:
      ADMIN_PASSWORD: admin
    volumes:
      - fuseki-data:/fuseki
      - ./ontology:/data/ontology
      - ./kg:/data/kg
      - ./shacl:/data/shacl

  streamlit:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hcmo-kgqa-ui
    ports:
      - "8501:8501"
    env_file:
      - .env
    depends_on:
      - fuseki
    volumes:
      - ./ontology:/app/ontology
      - ./kg:/app/kg
      - ./shacl:/app/shacl
      - ./sparql:/app/sparql
      - ./app:/app/app

volumes:
  fuseki-data:
